name: train-the-game
channels:
  - defaults
dependencies:
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=pyhd3eb1b0_3
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.3=hb1e8313_2
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1h=haf1e3a3_0
  - pip=20.2.4=py38_0
  - python=3.8.5=h26836e1_1
  - readline=8.0=h1de35cc_0
  - setuptools=50.3.0=py38h0dc7051_1
  - sqlite=3.33.0=hffcf06c_0
  - tk=8.6.10=hb0a8c7a_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - cycler==0.10.0
    - dataclasses==0.6
    - future==0.18.2
    - joblib==0.17.0
    - kiwisolver==1.3.1
    - matplotlib==3.3.2
    - numpy==1.19.4
    - pandas==1.1.4
    - pillow==8.0.1
    - pygame==2.0.0.dev6
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2020.4
    - scikit-learn==0.23.2
    - scipy==1.5.3
    - six==1.15.0
    - sklearn==0.0
    - threadpoolctl==2.1.0
    - torch==1.7.0
    - torchvision==0.8.1
    - typing-extensions==3.7.4.3
